### ISSUE TITLE
Can this be ran on JDK 8?

### ISSUE THREAD

**Issue by DotaUw** [odota/parser#20]
Can I use JDK 8?

**Comment by howardchung** [comment]
yes, it should work

**Comment by DotaUw** [comment]
I am getting this error.

Exception in thread "main" java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

**Comment by howardchung** [comment]
That sounds like you already have something running on the port (maybe another instance of the parser)
