### ISSUE TITLE
Exception while parsing

### ISSUE THREAD

**Issue by Levoncher** [odota/parser#29]
Hello. I am using jdk 12.0.2 The text of the error is as follows:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
skadistats.clarity.ClarityException: oops. no provider found for required usage point interface opendota.processors.warding.OnWardExpired
	at skadistats.clarity.processor.runner.ExecutionModel.requireProvider(ExecutionModel.java:123)
	at skadistats.clarity.processor.runner.ExecutionModel.requireEventListener(ExecutionModel.java:135)
	at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:79)
	at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:49)
	at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:37)
	at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:35)
	at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:28)
	at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:43)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:37)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at opendota.Parse.<init>(Parse.java:177)
	at opendota.Main$MyHandler.handle(Main.java:27)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by howardchung** [comment]
I believe clarity only runs on JDK 8. @spheenik can confirm?

**Comment by spheenik** [comment]
Yes, only JDK8 is supported atm.
Looks like there is a problem with reflection in this case, as clarity cannot find the provider for `@OnWardExpired`.

**Comment by Levoncher** [comment]
Thank you for the reply! Was very helpful.
